import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { createSupabaseServerClient } from '@/lib/supabase-server';
import { PublicPortfolio } from '@/components/public-portfolio';

type Props = { params: Promise<{ username: string }>; searchParams: Promise<{ domain?: string }> };
async function profileFor(username: string, domain?: string) { const supabase = await createSupabaseServerClient(); const query = supabase.from('profiles').select('*'); const { data } = username === '__domain__' && domain ? await query.eq('custom_domain', domain).maybeSingle() : await query.eq('username', username).maybeSingle(); return data; }
export async function generateMetadata({ params, searchParams }: Props): Promise<Metadata> { const { username } = await params; const { domain } = await searchParams; const profile = await profileFor(username, domain); if (!profile) return { title: 'Portfolio not found' }; const title = `${profile.full_name} — Professional Portfolio`; const description = profile.summary || `Professional portfolio for ${profile.full_name}.`; const image = profile.photo_url ? [{ url: profile.photo_url }] : undefined; return { title, description, openGraph: { title, description, type: 'profile', images: image }, twitter: { card: 'summary_large_image', title, description, images: profile.photo_url ? [profile.photo_url] : undefined } }; }
export default async function PortfolioPage({ params, searchParams }: Props) { const { username } = await params; const { domain } = await searchParams; const profile = await profileFor(username, domain); if (!profile) notFound(); const supabase = await createSupabaseServerClient(); const [{ data: projects }, { data: experiences }, { data: skills }] = await Promise.all([supabase.from('projects').select('*').eq('profile_id', profile.id).order('order_index'), supabase.from('experiences').select('*').eq('profile_id', profile.id).order('order_index'), supabase.from('skills').select('*').eq('profile_id', profile.id).order('order_index')]); return <PublicPortfolio profile={profile} projects={projects || []} experiences={experiences || []} skills={skills || []} />; }
